imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ZenSideCoreBundle/Resources/config/config.yml }
    - { resource: @ZenSideDemoBundle/Resources/config/config.yml }
