app_routes:
    resource: "@AppBundle/Controller/"
    type:     annotation

# JS ROUTING
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_routing:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"

app_api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routing_rest.yml"