<?php

namespace ZenSide\DemoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurnitureRepository extends EntityRepository
{
}
